### ISSUE TITLE
Please remove picture of "pacani"

### ISSUE THREAD

**Issue by VoronkovsAleksandrs** [artem-mevsha/chrome-fucking-advice#1]
chrome-fucking-advice/fucking-great-advice/img/4.jpg

Definitely this pic doesn't suit initial concept of adviser so it less here :)
Thank you!)

**Comment by artem-mevsha** [comment]
Hello @VoronkovsAleksandrs ! Thanks for your advice :-)
Main idea was to add a lot of images like this and show them depending on text from advice:
![screen shot 2018-01-04 at 18 31 24](https://user-images.githubusercontent.com/5147415/34573700-a8e32500-f17d-11e7-9bd7-2dadb1d65bfb.png)

But right now I don't want to do this so yes, it would be better to remove "pacani" from pictures folder

**Comment by VoronkovsAleksandrs** [comment]
@artem-mevsha yeap, u have great wallpapers there, don't need to show all of those trash there :D
