### ISSUE TITLE
Название новой вкладки

### ISSUE THREAD

**Issue by teamkiller7112** [artem-mevsha/chrome-fucking-advice#2]
На текущий момент заголовок новой вкладки такой: chrome://newtab.
Было бы удобно вернуть стандартное название: новая вкладка.

**Comment by artem-mevsha** [comment]
@teamkiller7112 Наконец-то нашел время обновить приложение. Добавил локализацию для трёх языков: английского, русского и украинского. В новой версии название новой вкладки должно быть "New tab" или "Новая вкладка", в зависимости от языка ОС/браузера. 

Спасибо за issue, прошу прощения за ответ через стольких долгих месяцев :-)

**Comment by teamkiller7112** [comment]
@artem-mevsha 
Круто, спасибо!
